import PageTitle from '../../components/ui/PageTitle';
import EmptyState from '../../components/ui/EmptyState';
import StatusBadge from '../../components/ui/StatusBadge';
import { agfGates } from '../../data/agfGates';
import { mockProjects } from '../../data/mockProjects';
import { calculateGate3Health } from '../../utils/gate3Health';
import { getGate3Status } from '../../utils/gate3Status';
import { mockGate3PendingItems } from '../../data/mockGate3PendingItems';
import { mockGate3Risks } from '../../data/mockGate3Risks';
import { mockGate3Gaps } from '../../data/mockGate3Gaps';
import { mockGate3Decisions } from '../../data/mockGate3Decisions';
import { mockGate3Dependencies } from '../../data/mockGate3Dependencies';
import { mockGate3Deliverables } from '../../data/mockGate3Deliverables';
import { mockGate3ChangeRequests } from '../../data/mockGate3ChangeRequests';
import { mockGate3Issues } from '../../data/mockGate3Issues';
import { navigateTo } from '../../utils/navigation';
const variant=(v)=>['Crítico','Bloqueado'].includes(v)?'critico':v==='Em atenção'||v==='Próximo'?'atencao':v==='Concluído'?'sucesso':'info';
export default function ProjectAgfJourneyPage({ projectId }){const project=mockProjects.find(p=>p.id===projectId); if(!project) return <EmptyState title="Projeto não encontrado" description="Volte ao portfólio para acessar a Jornada AGF de um projeto válido."><button onClick={()=>navigateTo('/portfolio')} className="rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-700">Voltar ao Portfólio</button></EmptyState>; const by=(items)=>items.filter(i=>i.projectId===projectId); const health=calculateGate3Health({pendingItems:by(mockGate3PendingItems),risks:by(mockGate3Risks),gaps:by(mockGate3Gaps),decisions:by(mockGate3Decisions),dependencies:by(mockGate3Dependencies),deliverables:by(mockGate3Deliverables),changeRequests:by(mockGate3ChangeRequests),issues:by(mockGate3Issues)}); const statusFor=(gate)=>gate.id<project.currentGate?'Concluído':gate.id>project.currentGate?'Próximo':gate.id===3?getGate3Status(project,health.status):'Em andamento'; return <div className="space-y-6"><PageTitle title={`Jornada AGF — ${project.name}`} subtitle="Gates 0 a 5 vinculados ao projeto selecionado, com destaque do gate atual e acesso ao Gate 3 operacional."/><section className="rounded-2xl bg-slate-900 p-6 text-white shadow-lg"><p className="text-xs font-bold uppercase tracking-wider text-blue-300">Cliente → Projeto → Time → Jornada AGF → Gate 3</p><h2 className="mt-2 text-2xl font-bold">{project.clientName}</h2><p className="mt-2 text-sm text-slate-300">Gate atual: Gate {project.currentGate} • Saúde simulada Gate 3: {health.status}</p><div className="mt-5 flex flex-wrap gap-3"><button onClick={()=>navigateTo(`/projetos/${project.id}`)} className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-slate-900 hover:bg-slate-100">Voltar ao Projeto</button><button onClick={()=>navigateTo(`/projetos/${project.id}/agf/gate/3`)} className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Acessar Gate 3</button></div></section><div className="space-y-4">{agfGates.map(g=>{const status=statusFor(g);return <article key={g.id} className={`rounded-2xl border p-6 shadow-sm ${g.id===project.currentGate?'border-blue-300 bg-blue-50':'border-slate-200 bg-white'}`}><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Gate {g.id}</p><h3 className="mt-1 text-lg font-semibold text-slate-900">{g.name}</h3><p className="mt-2 text-sm text-slate-600">{g.objective}</p></div><StatusBadge variant={variant(status)}>{status}</StatusBadge></div>{g.id===3&&<button onClick={()=>navigateTo(`/projetos/${project.id}/agf/gate/3`)} className="mt-4 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-700">Abrir módulo operacional Gate 3</button>}</article>})}</div></div>}
